modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "explorersfriend"
version = "${version}"
displayName = "The Explorer's Friend"
description = "Fully server-side browser world map."

[[mixins]]
config = "explorersfriend.mixins.json"

[[dependencies.explorersfriend]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,21.6)"
ordering = "NONE"
side = "SERVER"

[[dependencies.explorersfriend]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5]"
ordering = "NONE"
side = "SERVER"
